package org.example.supermarketwebapp.Utilities;

import org.example.supermarketwebapp.Entities.Category;
import org.example.supermarketwebapp.Entities.Product;
import org.example.supermarketwebapp.Repositories.CategoryRepository;
import org.example.supermarketwebapp.Repositories.ProductRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import java.util.logging.Logger;

@Component
public class DatabaseUtility {
    @Autowired
    ProductRepository productRepository;
    @Autowired
    CategoryRepository categoryRepository;
    public void initDatabase(){
        Logger.getLogger("Database utility").info("Seeding the database");
        initCategories();
        initProducts();

    }

    private void initProducts() {
        Product[] products = {
                new Product("Pain aux céréales", 24.90, "Pain moelleux aux céréales, idéal pour des petits déjeuners sains et équilibrés.", 1),
                new Product("Eau minérale naturelle", 9.90, "Eau minérale pure et rafraîchissante, issue des sources naturelles préservées.", 1),
                new Product( "Pizza surgelée 4 fromages", 39.90, "Pizza généreusement garnie de quatre fromages fondants, prête en quelques minutes pour un repas rapide.", 1 ),
                new Product( "Thé vert bio", 32.90, "Thé vert biologique aux arômes subtils, riche en antioxydants et parfait pour une pause détente.", 1),
                new Product( "Biscuits au chocolat", 17.90, "Délicieux biscuits croustillants au chocolat, parfaits pour accompagner une pause café ou thé.", 1),
                new Product( "Légumes surgelés", 29.90, "Assortiment de légumes surgelés, pratiques et prêts à être cuisinés pour des repas équilibrés.", 1),
                new Product( "Riz basmati", 27.90, "Riz basmati parfumé et léger, idéal pour accompagner vos plats exotiques ou traditionnels.", 1),
                new Product( "Poisson frais", 99.90, "Filet de poisson frais de la mer, riche en protéines et en acides gras essentiels pour une alimentation saine.", 1),
                new Product( "Barre énergétique aux fruits secs", 14.90, "Barre énergétique naturelle aux fruits secs, parfaite pour une pause énergétique pendant vos activités.", 1),
                new Product( "Eau pétillante", 12.90, "Eau minérale pétillante, rafraîchissante et désaltérante, idéale pour accompagner vos repas.", 1),
                new Product( "Pâtes alimentaires", 14.90, "Pâtes alimentaires de qualité supérieure, riches en glucides et parfaites pour des plats savoureux.", 1),
                new Product( "Huile d'olive extra vierge", 49.90, "Huile d'olive extra vierge de première pression à froid, aux arômes subtils et aux bienfaits pour la santé.", 1),
                new Product( "Sardines à l'huile", 19.90, "Sardines à l'huile de qualité supérieure, riches en oméga-3 et parfaites pour accompagner vos plats méditerranéens.", 1),
                new Product( "Miel de fleurs sauvages", 64.90, "Miel de fleurs sauvages, récolté avec soin dans les régions préservées, aux arômes riches et délicats.", 1),
                new Product( "Yaourt aux fruits", 22.90, "Yaourt naturel aux fruits frais, source de calcium et de probiotiques pour une digestion saine.", 1),
                new Product( "Beurre doux", 34.90, "Beurre doux de qualité, idéal pour tartiner sur du pain frais ou pour cuisiner vos plats préférés.", 1),
                new Product( "Salade verte", 17.90, "Salade verte croquante et fraîche, prête à être dégustée seule ou en accompagnement de vos plats.", 1),
                new Product( "Compote de pommes", 21.90, "Compote de pommes maison, sans sucres ajoutés, parfaite pour une pause gourmande et équilibrée.", 1),
                new Product( "Chips de pommes de terre", 19.90, "Chips croustillantes de pommes de terre, assaisonnées avec soin pour un plaisir gourmand à tout moment.", 1),
                new Product( "Eau de coco", 29.90, "Eau de coco pure et rafraîchissante, naturellement hydratante et riche en électrolytes essentiels.", 1),
                new Product(  "Sauce tomate", 14.90, "Sauce tomate savoureuse, préparée avec des tomates mûries au soleil et des herbes fraîches, parfaite pour vos pâtes et pizzas.", 1),
                new Product("Lait", 4.00, "Lait frais de qualité, idéal pour vos boissons chaudes, céréales et recettes de cuisine.", 1),
                new Product( "Pois chiches en conserve", 9.90, "Pois chiches en conserve, prêts à être utilisés dans vos recettes de curry, salades ou houmous maison.", 1),
                new Product( "Détergent pour lave-vaisselle", 49.90, "Détergent puissant conçu pour éliminer les taches les plus tenaces de vos assiettes et couverts.", 2),
                new Product( "Nettoyant multi-surfaces", 24.90, "Nettoyant polyvalent efficace sur toutes les surfaces, laissant une odeur fraîche et agréable.", 2),
                new Product( "Désinfectant pour salle de bain", 39.90, "Élimine les germes et les bactéries tout en laissant vos surfaces de salle de bain étincelantes de propreté.", 2),
                new Product( "Vinaigre blanc", 19.90, "Produit naturellement efficace pour désinfecter, détartrer et faire briller vos surfaces sans laisser de résidus chimiques.", 2),
                new Product( "Éponges à récurer", 9.90, "Éponges robustes et durables pour éliminer les saletés incrustées sur les surfaces sans les rayer.", 2),
                new Product( "Déboucheur liquide", 34.90, "Solution rapide et efficace pour déboucher les canalisations et éliminer les obstructions.", 2),
                new Product( "Lessive en poudre", 59.90, "Formule concentrée pour un lavage en profondeur, éliminant les taches tout en préservant les couleurs de vos vêtements.", 2),
                new Product("Assouplissant textile", 44.90, "Assouplissant à la formule anti-statique, laissant vos vêtements doux, frais et faciles à repasser.", 2),
                new Product( "Nettoyant pour vitres", 29.90, "Nettoyant sans traces pour des fenêtres, miroirs et surfaces vitrées impeccables et éclatantes de propreté.", 2),
                new Product( "Détachant textile", 32.90, "Élimine efficacement les taches les plus tenaces sur les tissus et les vêtements, préservant leur couleur et leur texture.", 2),
                new Product( "Pastilles pour lave-vaisselle", 64.90, "Pastilles tout-en-un pour un nettoyage optimal de votre vaisselle, éliminant les résidus alimentaires et laissant une brillance éclatante.", 2),
                new Product( "Nettoyant pour four", 47.90, "Nettoyant puissant pour éliminer les graisses cuites incrustées dans votre four, laissant une fraîcheur agréable.", 2),
                new Product( "Dégraissant cuisine", 39.90, "Formule spéciale pour dégraisser les surfaces de cuisine, éliminant les résidus de graisse sans effort.", 2),
                new Product("Détartrant pour cafetière", 24.90, "Détartrant efficace pour prolonger la durée de vie de votre cafetière en éliminant les dépôts de calcaire.", 2),
                new Product( "Désodorisant pour maison", 29.90, "Neutralise les mauvaises odeurs et laisse un parfum frais et agréable dans toute la maison.", 2),
                new Product( "Cire pour meubles", 54.90, "Cire nourrissante pour bois, protégeant et ravivant la beauté naturelle de vos meubles.", 2),
                new Product("Détachant tapis et moquettes", 42.90, "Formule puissante pour éliminer les taches incrustées dans les tapis et les moquettes, laissant une fraîcheur agréable.", 2),
                new Product( "Désinfectant pour surfaces sensibles", 37.90, "Désinfectant doux mais efficace pour les surfaces sensibles, éliminant les germes sans les endommager.", 2),
                new Product( "Nettoyant pour cuvette de toilette", 29.90, "Gel nettoyant pour éliminer les taches et les dépôts dans la cuvette de votre toilette, laissant une fraîcheur durable.", 2),
                new Product( "Déboucheur biologique", 69.90, "Formule écologique pour déboucher les canalisations sans produits chimiques agressifs, respectant l'environnement.", 2),
                new Product( "Nettoyant pour lave-linge", 49.90, "Élimine les résidus de saleté et les mauvaises odeurs de votre lave-linge, prolongeant sa durée de vie.", 2),
                new Product( "Cristaux de soude", 19.90, "Produit polyvalent pour nettoyer, dégraisser et désodoriser diverses surfaces, idéal pour une utilisation écologique.", 2),
                new Product( "Savon liquide pour les mains", 22.90, "Savon doux et hydratant pour les mains, laissant une sensation de fraîcheur et de propreté après chaque lavage.", 2),
                new Product( "Casque audio sans fil", 49.99, "Casque audio sans fil avec technologie Bluetooth, offrant un son clair et des basses profondes pour une expérience d'écoute immersive.", 3),
                new Product( "Enceinte Bluetooth portable", 29.99, "Enceinte Bluetooth portable, compacte et puissante, idéale pour écouter votre musique préférée où que vous soyez.", 3),
                new Product( "Smartphone dernière génération", 699.99, "Smartphone dernière génération avec un écran haute résolution, un appareil photo avancé et une autonomie exceptionnelle pour rester connecté en toutes circonstances.",3),
                new Product("Écouteurs intra-auriculaires", 39.99, "Écouteurs intra-auriculaires légers et confortables, offrant un son équilibré et une isolation phonique pour une expérience musicale optimale.", 3),
                new Product("Montre connectée", 129.99, "Montre connectée élégante et fonctionnelle, dotée de multiples fonctionnalités telles que le suivi d'activité, la fréquence cardiaque et les notifications intelligentes.", 3),
                new Product("Appareil photo numérique", 399.99, "Appareil photo numérique haute performance avec capteur CMOS, objectif polyvalent et fonctionnalités avancées pour capturer des moments inoubliables avec une qualité exceptionnelle.", 3),
                new Product("Tablette tactile", 299.99, "Tablette tactile avec un écran HD lumineux, un processeur rapide et une grande autonomie, parfaite pour le travail, le divertissement et la créativité.", 3),
                new Product("Imprimante tout-en-un", 159.99, "Imprimante tout-en-un compacte et polyvalente, offrant une impression de haute qualité, une numérisation rapide et une connectivité sans fil pour une utilisation facile.", 3),
                new Product("Clavier et souris sans fil", 39.99, "Ensemble clavier et souris sans fil élégant et ergonomique, offrant une connexion fiable et un confort d'utilisation optimal pour une productivité accrue.", 3),
                new Product("Disque dur externe", 99.99, "Disque dur externe compact et robuste, offrant une grande capacité de stockage et une vitesse de transfert rapide pour sauvegarder et partager vos données en toute sécurité.", 3),
                new Product("Téléviseur OLED 65 pouces", 1799.99, "Téléviseur OLED 4K HDR avec des couleurs riches et un contraste profond pour une expérience cinématographique à domicile inégalée.", 3),
                new Product("Console de jeux vidéo", 499.99, "Console de jeux vidéo dernière génération, offrant des graphismes époustouflants, une expérience de jeu immersive et une bibliothèque de jeux variée.", 3),
                new Product("Routeur Wi-Fi 6", 129.99, "Routeur Wi-Fi 6 ultra-rapide avec une couverture étendue, des performances exceptionnelles et une sécurité avancée pour une connectivité sans faille dans toute la maison.", 3),
                new Product("Écran d'ordinateur LED 27 pouces", 299.99, "Écran d'ordinateur LED Full HD avec des couleurs vives et un temps de réponse rapide, idéal pour le travail, les jeux et le divertissement multimédia.", 3),
                new Product("Caméra de sécurité intelligente", 79.99, "Caméra de sécurité intelligente avec vision nocturne, détection de mouvement et fonctionnalités de surveillance à distance pour protéger votre domicile et votre famille.", 3),
                new Product("Écouteurs sans fil avec réduction de bruit", 149.99, "Écouteurs sans fil avec technologie de réduction de bruit active, offrant une expérience d'écoute immersive et sans interruption, où que vous soyez.", 3),
                new Product("Lecteur Blu-ray Ultra HD", 129.99, "Lecteur Blu-ray Ultra HD avec une qualité d'image exceptionnelle, une compatibilité étendue et des fonctionnalités avancées pour une expérience de divertissement à domicile ultime.", 3),
                new Product("Système audio surround 5.1", 399.99, "Système audio surround 5.1 avec un son immersif et une puissance exceptionnelle, idéal pour les films, la musique et les jeux vidéo.", 3),
                new Product("Station de recharge sans fil", 49.99, "Station de recharge sans fil élégante et pratique, compatible avec une large gamme de smartphones et d'accessoires pour une recharge rapide et facile.", 3),
                new Product("Casque de réalité virtuelle", 299.99, "Casque de réalité virtuelle haute performance, offrant des expériences immersives, des mondes virtuels époustouflants et des jeux captivants.", 3),
                new Product("Écouteurs intra-auriculaires", 39.99, "Écouteurs intra-auriculaires légers et confortables, offrant un son équilibré et une isolation phonique pour une expérience musicale optimale.", 3),
                new Product("Montre connectée", 129.99, "Montre connectée élégante et fonctionnelle, dotée de multiples fonctionnalités telles que le suivi d'activité, la fréquence cardiaque et les notifications intelligentes.", 3),
                new Product("Appareil photo numérique", 399.99, "Appareil photo numérique haute performance avec capteur CMOS, objectif polyvalent et fonctionnalités avancées pour capturer des moments inoubliables avec une qualité exceptionnelle.", 3),
                new Product("Tablette tactile", 299.99, "Tablette tactile avec un écran HD lumineux, un processeur rapide et une grande autonomie, parfaite pour le travail, le divertissement et la créativité.", 3),
                new Product("Imprimante tout-en-un", 159.99, "Imprimante tout-en-un compacte et polyvalente, offrant une impression de haute qualité, une numérisation rapide et une connectivité sans fil pour une utilisation facile.", 3),
                new Product("Clavier et souris sans fil", 39.99, "Ensemble clavier et souris sans fil élégant et ergonomique, offrant une connexion fiable et un confort d'utilisation optimal pour une productivité accrue.", 3),
                new Product("Disque dur externe", 99.99, "Disque dur externe compact et robuste, offrant une grande capacité de stockage et une vitesse de transfert rapide pour sauvegarder et partager vos données en toute sécurité.", 3),
                new Product("Téléviseur OLED 65 pouces", 1799.99, "Téléviseur OLED 4K HDR avec des couleurs riches et un contraste profond pour une expérience cinématographique à domicile inégalée.", 3),
                new Product("Console de jeux vidéo", 499.99, "Console de jeux vidéo dernière génération, offrant des graphismes époustouflants, une expérience de jeu immersive et une bibliothèque de jeux variée.", 3),
                new Product("Routeur Wi-Fi 6", 129.99, "Routeur Wi-Fi 6 ultra-rapide avec une couverture étendue, des performances exceptionnelles et une sécurité avancée pour une connectivité sans faille dans toute la maison.", 3),
                new Product("Écran d'ordinateur LED 27 pouces", 299.99, "Écran d'ordinateur LED Full HD avec des couleurs vives et un temps de réponse rapide, idéal pour le travail, les jeux et le divertissement multimédia.", 3),
                new Product("Caméra de sécurité intelligente", 79.99, "Caméra de sécurité intelligente avec vision nocturne, détection de mouvement et fonctionnalités de surveillance à distance pour protéger votre domicile et votre famille.", 3),
                new Product("Écouteurs sans fil avec réduction de bruit", 149.99, "Écouteurs sans fil avec technologie de réduction de bruit active, offrant une expérience d'écoute immersive et sans interruption, où que vous soyez.", 3),
                new Product("Lecteur Blu-ray Ultra HD", 129.99, "Lecteur Blu-ray Ultra HD avec une qualité d'image exceptionnelle, une compatibilité étendue et des fonctionnalités avancées pour une expérience de divertissement à domicile ultime.", 3),
                new Product("Système audio surround 5.1", 399.99, "Système audio surround 5.1 avec un son immersif et une puissance exceptionnelle, idéal pour les films, la musique et les jeux vidéo.", 3),
                new Product("Station de recharge sans fil", 49.99, "Station de recharge sans fil élégante et pratique, compatible avec une large gamme de smartphones et d'accessoires pour une recharge rapide et facile.", 3),
                new Product("Casque de réalité virtuelle", 299.99, "Casque de réalité virtuelle haute performance, offrant des expériences immersives, des mondes virtuels époustouflants et des jeux captivants.", 3),
                new Product("Haltères ajustables", 129.99, "Haltères ajustables pour la musculation à domicile, offrant une grande variété de poids et d'exercices pour un entraînement complet du corps.", 5),
                new Product("Sac de frappe", 149.99, "Sac de frappe résistant et durable, idéal pour les séances d'entraînement de boxe, de kickboxing et de fitness.", 5),
                new Product("Veste de running réfléchissante", 69.99, "Veste de running légère et respirante, dotée d'éléments réfléchissants pour une visibilité optimale pendant vos courses de nuit.", 5),
                new Product("Serviette de sport en microfibre", 12.99, "Serviette de sport en microfibre absorbante et séchage rapide, idéale pour vos séances d'entraînement, vos séances de yoga ou vos voyages.", 5),
                new Product("Roller en ligne", 79.99, "Roller en ligne confortable et stable, offrant une conduite fluide et un bon maintien pour des sorties urbaines ou de loisirs.", 5),
                new Product("Gilet de sauvetage", 39.99, "Gilet de sauvetage léger et ajustable, idéal pour la navigation de plaisance, le kayak ou toute autre activité nautique.", 5),
                new Product("Ballon de rugby", 34.99, "Ballon de rugby résistant et grip optimal, idéal pour les matchs et les entraînements sur le terrain.", 5),
                new Product("Élastique de résistance", 9.99, "Élastique de résistance polyvalent, idéal pour renforcer les muscles, améliorer la souplesse et la mobilité.", 5),
                new Product("Casque de vélo", 49.99, "Casque de vélo léger et aérodynamique, offrant une protection optimale et un ajustement confortable pour vos balades en vélo.", 5),
                new Product("Balle de tennis de table", 4.99, "Balle de tennis de table légère et durable, parfaite pour les matchs amicaux ou les compétitions sérieuses.", 5),
                new Product("Gants de gardien de but", 24.99, "Gants de gardien de but avec grip supérieur et protection renforcée, idéaux pour les matchs et les entraînements de football.", 5),
                new Product("Hamac de camping", 34.99, "Hamac de camping léger et compact, idéal pour se détendre et se reposer lors de vos aventures en plein air.", 5),
                new Product("Tapis de yoga épais", 39.99, "Tapis de yoga épais et confortable, offrant un amorti supplémentaire pour les poses d'étirement et de relaxation.", 5),
                new Product("Crème hydratante visage", 8.49, "Crème hydratante pour le visage, formulée avec des ingrédients naturels pour une hydratation en profondeur et une peau éclatante.", 6),
                new Product("Shampooing fortifiant", 5.99, "Shampooing fortifiant pour des cheveux forts et brillants, enrichi en protéines et en vitamines pour une action revitalisante.", 6),
                new Product("Gel douche revitalisant", 4.49, "Gel douche revitalisant, avec des extraits de plantes et des huiles essentielles pour une sensation de fraîcheur et de bien-être sous la douche.", 6),
                new Product("Déodorant naturel", 3.29, "Déodorant naturel sans aluminium, à base d'ingrédients doux et efficaces pour une protection longue durée et une sensation de fraîcheur.", 6),
                new Product("Crème solaire SPF 50", 12.99, "Crème solaire SPF 50 à large spectre, légère et non grasse, offrant une protection optimale contre les rayons UVA et UVB.", 6),
                new Product("Baume à lèvres nourrissant", 2.99, "Baume à lèvres nourrissant et hydratant, enrichi en beurre de karité et en vitamines pour des lèvres douces et soyeuses.", 6),
                new Product("Masque capillaire réparateur", 9.99, "Masque capillaire réparateur, formulé avec des huiles nourrissantes et des protéines pour restaurer la santé et la vitalité des cheveux.", 6),
                new Product("Sérum anti-âge", 19.99, "Sérum anti-âge puissant, enrichi en acide hyaluronique et en peptides pour réduire les rides, raffermir la peau et restaurer son éclat jeunesse.", 6),
                new Product("Démaquillant doux", 6.49, "Démaquillant doux et efficace, à base d'ingrédients naturels pour éliminer en douceur le maquillage et les impuretés, laissant la peau propre et fraîche.", 6),
                new Product("Huile démaquillante", 8.99, "Huile démaquillante légère et nourrissante, idéale pour éliminer le maquillage tenace et les impuretés tout en préservant l'hydratation de la peau.", 6),
                new Product("Crème contour des yeux", 15.99, "Crème contour des yeux hydratante et anti-âge, formulée pour réduire les cernes, les poches et les ridules autour des yeux, pour un regard éclatant de jeunesse.", 6),
                new Product("Mascara allongeant", 7.99, "Mascara allongeant et volumateur, avec une formule légère et durable pour des cils définis, longs et recourbés tout au long de la journée.", 6),
                new Product("Poudre bronzante", 10.99, "Poudre bronzante compacte, idéale pour un teint hâlé naturel toute l'année, avec une texture soyeuse et une tenue longue durée.", 6),
                new Product("Vernis à ongles longue tenue", 6.99, "Vernis à ongles longue tenue et haute brillance, disponible dans une gamme de teintes tendance pour des ongles parfaits en toutes occasions.", 6),
                new Product("Rouge à lèvres hydratant", 9.49, "Rouge à lèvres hydratant et longue tenue, enrichi en beurre de cacao et en vitamines pour des lèvres douces, lisses et éclatantes de couleur.", 6),
                new Product("Crayon eyeliner waterproof", 5.49, "Crayon eyeliner waterproof, avec une formule crémeuse et pigmentée pour un tracé précis et une tenue irréprochable toute la journée.", 6),
                new Product("Palette de maquillage", 29.99, "Palette de maquillage polyvalente, avec une sélection de fards à paupières, de blushs et de rouges à lèvres pour créer une infinité de looks.", 6),
                new Product("Gel coiffant fixation forte", 8.99, "Gel coiffant fixation forte, pour une tenue longue durée et une coiffure structurée, sans résidus collants ni effet carton.", 6),
                new Product("Eau micellaire nettoyante", 7.49, "Eau micellaire nettoyante et démaquillante, avec des micelles actives pour éliminer les impuretés et le maquillage tout en douceur, sans rinçage.", 6),
                new Product("Crème solaire teintée SPF 30", 14.99, "Crème solaire teintée SPF 30, légèrement teintée pour un effet bonne mine immédiat, tout en protégeant la peau des rayons UV nocifs.", 6),
                new Product("Fixateur de maquillage", 9.99, "Fixateur de maquillage transparent, pour fixer et prolonger la tenue du maquillage tout au long de la journée, sans effet collant ni dessèchement de la peau.", 6),
                new Product("Crayon à sourcils waterproof", 6.49, "Crayon à sourcils waterproof, avec une texture crémeuse et une pointe fine pour redessiner et définir les sourcils avec précision, pour un résultat naturel et longue tenue.", 6),
                new Product("Masque purifiant", 8.49, "Masque purifiant à l'argile, pour nettoyer en profondeur les pores et éliminer les impuretés, laissant la peau fraîche, douce et éclatante.", 6),
                new Product("Canapé convertible en tissu", 499.99, "Canapé convertible en tissu confortable et élégant, idéal pour les petits espaces et les invités occasionnels.", 7),
                new Product("Table basse en bois massif", 149.99, "Table basse en bois massif avec finition naturelle, ajoutant une touche rustique et chaleureuse à votre salon.", 7),
                new Product("Bibliothèque modulable", 299.99, "Bibliothèque modulable en bois, offrant un espace de rangement polyvalent pour vos livres, objets de décoration et souvenirs.", 7),
                new Product("Chaise de bureau ergonomique", 129.99, "Chaise de bureau ergonomique avec support lombaire et réglages personnalisés pour un confort optimal pendant de longues heures de travail.", 7),
                new Product("Lit double avec tête de lit rembourrée", 699.99, "Lit double avec tête de lit rembourrée et cadre en bois solide, offrant un confort et un style luxueux à votre chambre à coucher.", 7),
                new Product("Armoire à portes coulissantes", 449.99, "Armoire à portes coulissantes en bois, avec une disposition intérieure optimisée pour un rangement pratique et organisé de vos vêtements et accessoires.", 7),
                new Product("Ensemble de salle à manger", 799.99, "Ensemble de salle à manger comprenant une table en bois massif et des chaises rembourrées, idéal pour les repas en famille et les dîners entre amis.", 7),
                new Product("Étagère murale design", 79.99, "Étagère murale design en métal et bois, ajoutant une touche moderne et fonctionnelle à votre salon, chambre à coucher ou bureau.", 7),
                new Product("Commode à tiroirs", 249.99, "Commode à tiroirs spacieuse et élégante, offrant un rangement pratique et esthétique pour vos vêtements, linge de maison et accessoires.", 7),
                new Product("Fauteuil de lecture confortable", 199.99, "Fauteuil de lecture confortable avec revêtement en tissu doux et accoudoirs rembourrés, idéal pour créer un coin lecture confortable dans votre salon ou votre chambre.", 7),
                new Product("Bureau d'angle avec étagères", 349.99, "Bureau d'angle avec étagères de rangement intégrées, offrant un espace de travail fonctionnel et organisé pour votre bureau à domicile ou votre espace de travail.", 7),
                new Product("Buffet en bois et métal", 579.99, "Buffet en bois et métal avec finition industrielle, offrant un rangement spacieux et stylé pour votre vaisselle, verres et autres objets de décoration.", 7),
                new Product("Table de chevet moderne", 89.99, "Table de chevet moderne avec tiroir et étagère, idéale pour ranger vos livres, lampe de chevet et autres essentiels de nuit à portée de main.", 7),
                new Product("Canapé d'angle en cuir", 899.99, "Canapé d'angle en cuir élégant et confortable, offrant un espace généreux pour toute la famille et les invités.", 7),
                new Product("Table de salle à manger extensible", 999.99, "Table de salle à manger extensible en bois massif, idéale pour les grands repas de famille et les réceptions, avec un design élégant et pratique.", 7),
                new Product("Pouf en tissu multifonction", 49.99, "Pouf en tissu multifonction, à la fois repose-pieds, siège d'appoint et table basse, ajoutant confort et polyvalence à votre salon ou votre espace de détente.", 7),
                new Product("Table console moderne", 349.99, "Table console moderne avec tiroirs de rangement et étagères ouvertes, idéale pour habiller un couloir ou un salon avec style et fonctionnalité.", 7),
                new Product("Lit superposé pour enfants", 499.99, "Lit superposé pour enfants en bois massif, offrant un couchage confortable et sécurisé pour les frères et sœurs ou les invités, tout en économisant de l'espace dans la chambre.", 7),
                new Product("Étagère à chaussures", 79.99, "Étagère à chaussures pratique et compacte, offrant un rangement ordonné pour vos chaussures dans l'entrée, le dressing ou le couloir.", 7),
                new Product("Table de jardin en aluminium", 299.99, "Table de jardin en aluminium résistant et facile à entretenir, parfaite pour les repas en plein air et les moments de détente dans votre jardin ou sur votre terrasse.", 7),
                new Product("Chaise longue inclinable", 179.99, "Chaise longue inclinable en tissu résistant aux intempéries, idéale pour se détendre et profiter du soleil dans le jardin, sur la terrasse ou au bord de la piscine.", 7),
                new Product("Table de bar avec tabourets", 399.99, "Table de bar avec tabourets assortis, parfaite pour créer un coin bar convivial dans votre cuisine, votre salle à manger ou votre espace de divertissement.", 7),
                new Product("Banc de rangement en bois", 129.99, "Banc de rangement en bois avec coussin rembourré, offrant un siège confortable et un espace de stockage pratique pour vos chaussures et accessoires dans l'entrée ou le couloir.", 7),
                new Product("Étagère à vin murale", 69.99, "Étagère à vin murale en métal noir, offrant un rangement élégant et pratique pour vos bouteilles de vin, idéale pour la cuisine, la salle à manger ou le cellier.", 7),
                new Product("Ensemble de jardin en résine tressée", 899.99, "Ensemble de jardin en résine tressée comprenant une table, des chaises et des coussins confortables, parfait pour créer un espace de détente élégant et confortable à l'extérieur.", 7),
                new Product("Chaise pliante en bois", 49.99, "Chaise pliante en bois avec dossier incliné, idéale pour les événements en plein air, les pique-niques et les barbecues, facile à ranger et à transporter.", 7),
                new Product("Meuble TV avec rangement", 299.99, "Meuble TV moderne avec rangement intégré, idéal pour organiser vos appareils électroniques, DVD et objets de décoration dans le salon ou la salle de divertissement.", 7),
                new Product("Lit gigogne en bois massif", 549.99, "Lit gigogne en bois massif avec tiroirs de rangement, offrant un couchage confortable et un espace de stockage pratique pour les chambres d'enfants ou les espaces invités.", 7),
                new Product("Lego Star Wars Millennium Falcon", 149.99, "Lego Star Wars Millennium Falcon, un ensemble de construction emblématique comprenant des personnages emblématiques, des détails authentiques et des fonctionnalités impressionnantes.", 8),
                new Product("Poupée Barbie Dreamhouse", 99.99, "Poupée Barbie Dreamhouse, une maison de poupée élégante avec des accessoires et des fonctionnalités interactives pour des heures de jeu imaginatif.", 8),
                new Product("Voiture télécommandée tout-terrain", 49.99, "Voiture télécommandée tout-terrain avec une conception robuste et des capacités de conduite hors route, idéale pour les amateurs de sensations fortes.", 8),
                new Product("Jeux de construction Magna-Tiles", 39.99, "Jeux de construction Magna-Tiles, des tuiles magnétiques colorées permettant aux enfants de créer et de construire des formes en 3D, favorisant la créativité et la pensée spatiale.", 8),
                new Product("Pistolet Nerf Elite", 29.99, "Pistolet Nerf Elite, un blaster à fléchettes en mousse pour des batailles passionnantes et sécurisées entre amis.", 8),
                new Product("Puzzle 3D du château de Disney", 19.99, "Puzzle 3D du château de Disney, un puzzle en trois dimensions reproduisant le célèbre château de conte de fées pour une expérience de construction magique.", 8),
                new Product("Peluche Licorne arc-en-ciel", 14.99, "Peluche Licorne arc-en-ciel, une peluche douce et colorée qui apporte de la magie et du réconfort à chaque câlin.", 8),
                new Product("Play-Doh Fun Factory", 9.99, "Play-Doh Fun Factory, un ensemble de jeu classique pour modeler et créer avec de la pâte à modeler colorée et des accessoires amusants.", 8),
                new Product("Set de train en bois", 59.99, "Set de train en bois avec rails, locomotive et wagons, offrant aux enfants des heures de jeu créatif et d'exploration.", 8),
                new Product("Figurine Spider-Man", 12.99, "Figurine Spider-Man articulée, inspirée du célèbre super-héros Marvel, parfaite pour les aventures imaginatives et le jeu de rôle.", 8),
                new Product("Livre de coloriage géant", 7.99, "Livre de coloriage géant avec des pages à thème varié, offrant aux enfants des heures de divertissement créatif et artistique.", 8),
                new Product("Jeu de société Monopoly", 24.99, "Jeu de société Monopoly, un classique intemporel qui offre des heures de plaisir en famille et entre amis, avec des achats, des négociations et de la stratégie.", 8),
                new Product("Puzzle en bois animaux de la jungle", 17.99, "Puzzle en bois animaux de la jungle, un puzzle éducatif et amusant qui aide les enfants à développer leurs compétences en résolution de problèmes et en coordination main-œil.", 8),
                new Product("Kit de magie pour débutants", 19.99, "Kit de magie pour débutants comprenant des tours de magie simples et amusants pour impressionner famille et amis.", 8),
                new Product("Poupée Ken", 9.99, "Poupée Ken, un compagnon de jeu pour Barbie et autres poupées, avec une garde-robe variée et des accessoires.", 8),
                new Product("Tente de jeu pour enfants", 39.99, "Tente de jeu pour enfants, un espace de jeu privé et amusant où les enfants peuvent laisser libre cours à leur imagination.", 8),
                new Product("Set de construction de circuits électriques", 29.99, "Set de construction de circuits électriques, permettant aux enfants de découvrir les bases de l'électricité et de créer leurs propres circuits fonctionnels.", 8),
                new Product("Puzzle des planètes du système solaire", 14.99, "Puzzle des planètes du système solaire, un puzzle éducatif pour apprendre et découvrir l'espace et les planètes.", 8),
                new Product("Kit de fabrication de slime", 12.99, "Kit de fabrication de slime, un ensemble complet pour créer des substances visqueuses et amusantes, idéal pour les activités sensorielles et les expériences scientifiques.", 8),
                new Product("Maquette de bateau en bois", 49.99, "Maquette de bateau en bois, un kit de construction détaillé pour les amateurs de modélisme naval et d'histoire maritime.", 8),
                new Product("Puzzle 3D du Taj Mahal", 24.99, "Puzzle 3D du Taj Mahal, un défi de construction pour recréer l'un des monuments les plus célèbres du monde.", 8),
                new Product("Jeu de construction en blocs magnétiques", 34.99, "Jeu de construction en blocs magnétiques, offrant aux enfants la possibilité de créer des structures complexes et imaginatives avec des pièces magnétiques.", 8),
                new Product("Pistolet à eau géant", 19.99, "Pistolet à eau géant pour des batailles d'eau épiques en plein air, idéal pour se rafraîchir pendant les chaudes journées d'été.", 8),
                new Product("Puzzle 3D de la tour Eiffel", 29.99, "Puzzle 3D de la tour Eiffel, une reproduction détaillée du célèbre monument parisien pour les amateurs de construction et d'architecture.", 8),
                new Product("Robot interactif pour enfants", 79.99, "Robot interactif pour enfants avec des fonctions de programmation de base et des réponses vocales, offrant une introduction ludique à la robotique et à la technologie.", 8),
                new Product("Set de pâte à modeler", 8.99, "Set de pâte à modeler comprenant différentes couleurs et accessoires pour créer des formes et des sculptures amusantes.", 8),
                new Product("Voiture de course télécommandée", 39.99, "Voiture de course télécommandée rapide et maniable, parfaite pour des courses endiablées à l'intérieur ou à l'extérieur.", 8),
                new Product("Dinosaure en peluche", 16.99, "Dinosaure en peluche douce et réaliste, idéal pour les amateurs de dinosaures et les enfants qui aiment les jouets en peluche.", 8),
                new Product("Harry Potter et la Pierre Philosophale", 12.99, "Harry Potter et la Pierre Philosophale, le premier livre de la série à succès de J.K. Rowling, racontant l'histoire magique du jeune sorcier Harry Potter.", 9),
                new Product("Le Seigneur des Anneaux : La Communauté de l'Anneau", 14.99, "Le Seigneur des Anneaux : La Communauté de l'Anneau, le premier tome de la trilogie épique de J.R.R. Tolkien, entraînant les lecteurs dans un voyage fantastique à travers la Terre du Milieu.", 9),
                new Product("1984", 9.99, "1984, le roman dystopique classique de George Orwell, explorant les thèmes de la surveillance gouvernementale, de la manipulation de l'information et de la liberté individuelle.", 9),
                new Product("Orgueil et Préjugés", 7.99, "Orgueil et Préjugés, le célèbre roman de Jane Austen, décrivant les complexités des relations sociales et des mariages dans la société anglaise du XIXe siècle.", 9),
                new Product("Le Petit Prince", 6.99, "Le Petit Prince, l'œuvre intemporelle d'Antoine de Saint-Exupéry, racontant l'histoire d'un jeune prince voyageant à travers les planètes et découvrant des leçons de vie profondes.", 9),
                new Product("Moby Dick", 11.99, "Moby Dick, le roman épique d'Herman Melville, suivant l'obsession du capitaine Achab pour la chasse à la baleine blanche légendaire.", 9),
                new Product("Le Hobbit", 10.99, "Le Hobbit, ou Un voyage inattendu, le conte fantastique de J.R.R. Tolkien, suivant les aventures du hobbit Bilbo Baggins dans sa quête pour récupérer le trésor gardé par le dragon Smaug.", 9),
                new Product("Crime et Châtiment", 8.99, "Crime et Châtiment, le chef-d'œuvre de Fiodor Dostoïevski, explorant les profondeurs de la conscience humaine à travers l'histoire de Rodion Raskolnikov et son crime.", 9),
                new Product("Les Misérables", 13.99, "Les Misérables, le roman épique de Victor Hugo, suivant les vies entrelacées de divers personnages dans la France du XIXe siècle, explorant des thèmes de justice, d'amour et de rédemption.", 9),
                new Product("Le Comte de Monte-Cristo", 12.49, "Le Comte de Monte-Cristo, l'œuvre magistrale d'Alexandre Dumas, racontant l'histoire de vengeance du marin Edmond Dantès après avoir été trahi et emprisonné à tort.", 9),
                new Product("L'Odyssée", 9.49, "L'Odyssée, le poème épique attribué à Homère, racontant le voyage aventureux du héros grec Odyssée après la guerre de Troie.", 9),
                new Product("Les Fleurs du Mal", 7.49, "Les Fleurs du Mal, le recueil de poèmes de Charles Baudelaire, explorant les thèmes de la beauté, de la passion et de la modernité dans la société du XIXe siècle.", 9),
                new Product("Anna Karénine", 11.49, "Anna Karénine, le roman magistral de Léon Tolstoï, décrivant les luttes intérieures et les dilemmes moraux des personnages vivant dans la Russie tsariste.", 9),
                new Product("Les Hauts de Hurlevent", 8.49, "Les Hauts de Hurlevent, le roman romantique d'Emily Brontë, dépeignant les passions destructrices et les vengeances dans une lande désolée du Yorkshire.", 9),
                new Product("La Divine Comédie", 15.99, "La Divine Comédie, l'épopée poétique de Dante Alighieri, décrivant son voyage à travers l'enfer, le purgatoire et le paradis, guidé par le poète romain Virgile et son amour Béatrice.", 9),
                new Product("Le Portrait de Dorian Gray", 10.49, "Le Portrait de Dorian Gray, le roman de Oscar Wilde, explorant les thèmes de la vanité, de la moralité et de la décadence à travers l'histoire du jeune Dorian Gray.", 9),
                new Product("Guerre et Paix", 14.49, "Guerre et Paix, le chef-d'œuvre de Léon Tolstoï, décrivant la vie de la haute société russe pendant les guerres napoléoniennes et explorant les thèmes de la guerre, de l'amour et de la destinée.", 9),
                new Product("Ordinateur portable HP Pavilion", 799.99, "Ordinateur portable HP Pavilion, équipé d'un processeur rapide, d'une grande capacité de stockage et d'un écran haute résolution, idéal pour le travail, les études et le divertissement.", 10),
                new Product("Apple MacBook Air", 1299.99, "Apple MacBook Air, ultraportable et puissant, doté d'un processeur M1, d'une autonomie longue durée et d'un superbe écran Retina, parfait pour les professionnels et les étudiants.", 10),
                new Product("Microsoft Surface Pro 7", 999.99, "Microsoft Surface Pro 7, polyvalent et portable, transformable en tablette ou en ordinateur portable, avec un stylet Surface pour une expérience tactile et créative exceptionnelle.", 10),
                new Product("Dell XPS 13", 1199.99, "Dell XPS 13, ultraportable et élégant, avec un écran InfinityEdge bord à bord, une puissance de traitement exceptionnelle et une autonomie prolongée, idéal pour les professionnels et les créatifs.", 10),
                new Product("Lenovo ThinkPad X1 Carbon", 1399.99, "Lenovo ThinkPad X1 Carbon, robuste et performant, doté de fonctionnalités de sécurité avancées, d'un clavier rétroéclairé et d'un écran haute résolution, conçu pour les professionnels exigeants.", 10),
                new Product("Asus ROG Zephyrus G14", 1499.99, "Asus ROG Zephyrus G14, un ordinateur portable de jeu compact et puissant, équipé d'un processeur Ryzen 9, d'une carte graphique RTX et d'un écran WQHD, conçu pour offrir des performances de jeu exceptionnelles.", 10),
                new Product("HP Envy 13", 899.99, "HP Envy 13, élégant et puissant, avec un design fin en métal, un écran tactile Full HD et des performances fiables, idéal pour les professionnels mobiles et les créatifs.", 10),
                new Product("Acer Swift 5", 999.99, "Acer Swift 5, ultraléger et polyvalent, avec un écran tactile Full HD, un processeur rapide et une autonomie longue durée, parfait pour les déplacements professionnels et la productivité quotidienne.", 10),
                new Product("Razer Blade 15", 1899.99, "Razer Blade 15, un ordinateur portable de jeu haut de gamme avec un design élégant en aluminium, un écran 4K OLED, un processeur Intel Core i7 et une carte graphique RTX, conçu pour les joueurs exigeants.", 10),
                new Product("Alienware Area-51m", 2499.99, "Alienware Area-51m, un ordinateur portable de jeu ultime avec un design futuriste, un écran 4K, un processeur Core i9, une carte graphique RTX 3080 et des fonctionnalités de refroidissement avancées, offrant des performances exceptionnelles pour les jeux et la création de contenu.", 10),
                new Product("Microsoft Surface Laptop 4", 1099.99, "Microsoft Surface Laptop 4, élégant et performant, avec un écran PixelSense tactile, un processeur rapide et une grande autonomie, conçu pour la productivité et le style.", 10),
                new Product("Lenovo Legion 5", 1299.99, "Lenovo Legion 5, un ordinateur portable de jeu puissant avec un écran haute résolution, un processeur Ryzen 7, une carte graphique RTX 3060 et un clavier rétroéclairé, offrant des performances exceptionnelles pour les joueurs passionnés.", 10),
                new Product("Dell Inspiron 15", 799.99, "Dell Inspiron 15, fiable et abordable, avec un écran tactile HD, un processeur Core i5 et une autonomie prolongée, idéal pour la productivité quotidienne et le divertissement multimédia.", 10),
                new Product("Asus ZenBook 14", 1099.99, "Asus ZenBook 14, fin et léger, avec un écran NanoEdge, un processeur Ryzen 5, un stockage SSD rapide et une autonomie longue durée, parfait pour les professionnels en déplacement.", 10),
                new Product("HP Spectre x360", 1299.99, "HP Spectre x360, élégant et polyvalent, avec un écran tactile 4K, un processeur Core i7, un stylet HP Tilt Pen et une conception convertible 2-en-1, offrant une expérience informatique exceptionnelle.", 10),
                new Product("Acer Predator Helios 300", 1399.99, "Acer Predator Helios 300, un ordinateur portable de jeu puissant avec un écran 144Hz, un processeur Core i7, une carte graphique RTX 3070 et un clavier RGB, conçu pour des performances de jeu immersives.", 10),
                new Product("Microsoft Surface Book 3", 1799.99, "Microsoft Surface Book 3, un ordinateur portable 2-en-1 polyvalent avec un écran détachable PixelSense, un processeur Core i7, une carte graphique GTX et une autonomie longue durée, offrant une flexibilité et des performances exceptionnelles.", 10)
        };

        for (Product product : products) {
           productRepository.save(product);
        }
    }

    private void initCategories() {
        Category[] categories={
                new Category("Alimentation"),
                new Category("Produits ménagers"),
                new Category("Electronique"),
                new Category("Vêtements"),
                new Category("Articles de sport"),
                new Category("Cosmétiques"),
                new Category("Meubles"),
                new Category("Jouets"),
                new Category("Livres"),
                new Category("Informatique")
        };
        for (Category category:categories){
            categoryRepository.save(category);
        }
    }

    public void dropTables() {

    }
}
